services:
  postgres:
    container_name: postgres-sql-car
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: car-management
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-car
    restart: unless-stopped

  keycloak:
    container_name: keycloak-car
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      KEYCLOAK_ADMIN: ibrahim
      KEYCLOAK_ADMIN_PASSWORD: 2024
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-sql-car
      DB_DATABASE: car-management
      DB_USER: postgres
      DB_PASSWORD: root
    ports:
      - "9090:8080"
    networks:
      - spring-car
    depends_on:
      - postgres
    command:
      - "start-dev"
    restart: unless-stopped

networks:
  spring-car:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local
