services:
  postgres:
    container_name: postgres-sql-car
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: car_management
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-car
    restart: unless-stopped
  keycloak:
    container_name: keycloak-car
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: ibrahim
      KEYCLOAK_ADMIN_PASSWORD: 2024
    networks:
      - spring-car
    command:
      - "start-dev"
networks:
  spring-car:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local