spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car-management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/master"
application:
  client: car
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088